config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'home#index'
  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def index
    @friends = Friend.all
  end

  def show
  end

  def new
    @friend = current_user.friends.build
  end

  def edit
  end

  def create
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_friend
    @friend = Friend.find(params[:id])
  end

  def friend_params
    params.require(:friend).permit(:user_id, :first_name, :last_name, :email, :phone, :twitter)
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "You are not friends with them!" if @friend.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :friend_user_id, class: "form-control form-control-lg", value: current_user.id, type: :hidden %>
  </div>

  <div class="field form-group">
    <%= form.text_field :first_name, class: "form-control form-control-lg", placeholder: "First name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name, class: "form-control form-control-lg", placeholder: "Last name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email, class: "form-control form-control-lg", placeholder: "Email" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone, class: "form-control form-control-lg", placeholder: "Phone number" %>
  </div>

  <div class="field form-group">
    <div class="input-group">
      <div class="input-group-prepend">
        <div class="input-group-text">@</div>
      </div>
      <%= form.text_field :twitter, class: "form-control form-control-lg", placeholder: "Twitter" %>
    </div>
  </div>

  <div class="actions pt-2">
    <div class="pb-2">
      <div class="row justify-content-md-center align-items-center">
        <div class="col col-4">
          <%= form.submit class: "btn btn-primary btn-block" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/friends/edit.html.erb
<div class="card">
  <div class="card-header">
    <h1>Edit Friend</h1>
  </div>

  <div class="card-body">
    <%= render 'form', friend: @friend %>

    <div class="">
      <div class="row justify-content-md-center align-items-center pb-2">
        <div class="col col-4">
          <%= link_to 'Back', friends_path, class: "btn btn-light btn-block" %>
        </div>
      </div>

      <div class="row justify-content-md-center align-items-center pb-2">
        <div class="col col-4">
          <%= link_to 'Show', @friend, class: "btn btn-secondary btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/friends/index.html.erb
<h1>My Friends</h1>

<br/>

<div class="table-responsive">
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <% next unless friend.user == current_user %>

        <tr>
          <td>
            <%= friend.first_name %>
            <%= friend.last_name %>
          </td>

          <td><%= friend.email %></td>

          <td><%= friend.phone %></td>

          <td><%= friend.twitter %></td>

          <td>
            <%= link_to friend do %>
              <i class="fas fa-address-card text-primary"></i>
            <% end %>
          </td>

          <td>
            <%= link_to edit_friend_path(friend) do %>
              <i class="fas fa-edit text-warning"></i>
            <% end %>
          </td>

          <td>
            <%= link_to friend, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fas fa-trash text-danger"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Add Friend', new_friend_path, class: "btn btn-primary" %>

app/views/friends/new.html.erb
<div class="card">
  <div class="card-header">
    <h1>Add Friend</h1>
  </div>

  <div class="card-body">
    <%= render 'form', friend: @friend %>

    <div class="">
      <div class="row justify-content-md-center align-items-center pb-2">
        <div class="col col-4">
          <%= link_to 'Back', friends_path, class: "btn btn-light btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>

  <div class="container-fluid">
    <p class="lead">
      <% unless @friend.twitter.empty? %>
        <i class="fab fa-twitter"></i>
        <%= "@#{@friend.twitter}" %>
      <% end %>
    </p>

    <p class="lead">
      <% unless @friend.email.empty? %>
        <i class="fas fa-envelope text-danger"></i>
        <%= @friend.email %>
      <% end %>
    </p>

    <p class="lead">
      <% unless @friend.phone.empty? %>
        <i class="fas fa-mobile text-dark"></i>
        <%= @friend.phone %>
      <% end %>
    </p>
  </div>

  <hr/>

  <div class="pt-2">
    <div class="row justify-content-md-center align-items-center pb-2">
      <div class="col col-4">
        <%= link_to 'Edit', edit_friend_path(@friend), class: "btn btn-primary btn-block" %>
      </div>
    </div>

    <div class="row justify-content-md-center align-items-center pb-2">
      <div class="col col-4">
        <%= link_to 'Back', friends_path, class: "btn btn-light btn-block" %>
      </div>
    </div>
  </div>
</div>

app/views/home/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">
      Made with <i class="fas fa-heart text-danger"></i> by <a href="//Twitter.com/sibalnirbhay">@sibalnirbhay</a>
    </span>
  </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <%= link_to 'Friends List App', root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'My Friends', friends_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Add Friend', new_friend_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
        
        <li class="nav-item active">
          <%= link_to 'About Me', home_about_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="jumbotron">
  <div class="text-center">
    <%= image_tag "memoji.jpg", class: "img-thumbnail rounded-circle shadow p-3 mb-3 bg-white rounded memoji" %>
  </div>

  <h1 class="display-4">
    Nirbhay Sibal
  </h1>

  <div class="container-fluid">
    <p class="lead">
      <i class="fab fa-twitter"></i>
      @sibalnirbhay
    </p>

    <p class="lead">
      <i class="fab fa-linkedin"></i>
      sibalnirbhay
    </p>

    <p class="lead">
      <i class="fas fa-envelope text-danger"></i>
      sibal.nirbhay@hotmail.com
    </p>

    <p class="lead">
      <i class="fas fa-mobile text-dark"></i>
      (469) 395-1318
    </p>
  </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="container p-2">
    <h1 class="display-4">Hello<%= ", #{current_user.email}!" if user_signed_in? %> 👋</h1>
  </div>

  <div class="container px-4 py-2">
    <p class="lead">
      This is a Friends List App. I created this just because I wanted to learn web development using Rails.
    </p>
  </div>

  <hr class="my-4">

  <div class="container px-4 py-2">
    <p>
      I followed <a href="https://youtu.be/fmyvWz5TUWg">this</a> Learn Ruby on Rails course on freeCodeCamp.org's YouTube channel, extensively instructed by <a href="http://Codemy.com">Codemy.com</a>'s John Elder (<i class="fab fa-twitter"></i> @flatplanet).

      <br/>
      <br/>

      This project involves a bunch of tools and technologies:
      <ul>
        <li>Ruby on Rails</li>
        <li>PostgreSQL</li>
        <li>SQLite</li>
        <li>HTML</li>
        <li>CSS</li>
        <li>Bootstrap</li>
        <li>JavaScript</li>
        <li>jQuery</li>
        <li>Heroku</li>
      </ul>

      <br/>

      Feel free to grab the code of this app from this <a href="https://github.com/sibalnirbhay/friends-list-RoR">GitHub repo</a> 🙏.
    </p>
  </div>

  <hr class="my-4">
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends List App</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>

    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %>

    <div class="container">
      <br/>

      <%= render 'layouts/alerts' if notice %>

      <%= yield %>
    </div>

    <%= render 'home/footer' %>
  </body>
</html>